# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: app_start.sh
      timeout: 300
      runas: root

  AfterInstall:
      - location: after_install.sh
        timeout: 1000
        runas: root

  ApplicationStart:
    - location: start_server.sh     
      timeout: 300
      runas: root
